FROM alpine:latest
MAINTAINER Manuel Ignacio Franco <maigfrga@gmail.com>
USER root
ADD ./tools /tools
RUN apk add py3-psycopg2 postgresql postgresql-dev postgresql
RUN mkdir -p /postgresql/data
RUN chown -R postgres:postgres /postgresql/*
RUN mkdir -p /run/postgresql
RUN chown -R postgres:postgres /run/postgresql/
USER postgres
ENV LANG en_US.utf8
ENV PGDATA /postgresql/data

RUN /tools/configure_postgresql.sh

CMD ["/tools/init_postgresql.sh"]
