FROM alpine:latest
MAINTAINER Manuel Ignacio Franco <maigfrga@gmail.com>
USER root

RUN mkdir /philo_alchemy
WORKDIR /philo_alchemy

RUN rm -rf /var/cache/apk/*
RUN apk add --update --no-cache bash alpine-sdk gcc git db-dev make autoconf automake libffi libffi-dev \
    boost boost-dev libtool libevent libevent-dev musl-dev \
    python3 python3-dev py3-virtualenv \
    openssh-client py3-psycopg2  \
    python3 pytest

RUN rm -rf /usr/bin/python && ln -s /usr/bin/python3 /usr/bin/python
RUN pip3 install flask flask-cors simplejson JSON-log-formatter rfc3987 strict-rfc3339 webcolors jsonschema sqlalchemy bcrypt  ipdb 

ENV PYTHONPATH /philo_core:/philo_alchemy

CMD ["tail", "-f", "/dev/null"]
