FROM alpine:latest
MAINTAINER Manuel Ignacio Franco <maigfrga@gmail.com>
USER root
RUN apk add --update bash && rm -rf /var/cache/apk/*
RUN apk add --update alpine-sdk
RUN apk add --no-cache gcc git db-dev make autoconf automake libffi libffi-dev
RUN apk add --no-cache boost boost-dev libtool libevent libevent-dev musl-dev
RUN apk add --no-cache python3 python3-dev py3-virtualenv
RUN apk add --no-cache openssh-client py3-psycopg2
RUN apk add --no-cache python3 pytest
RUN rm -rf /usr/bin/python && ln -s /usr/bin/python3 /usr/bin/python
RUN pip3 install flask flask-cors simplejson JSON-log-formatter rfc3987 strict-rfc3339 webcolors jsonschema sqlalchemy ipdb

ENV PYTHONPATH /philo_core:/philo_alchemy

CMD ["tail", "-f", "/dev/null"]
